### ISSUE TITLE
iBrowse crashes when started a second time

### ISSUE THREAD

**Issue by FabrizioRadica** [BlitterStudio/amiberry#703] opened 2020-10-19 20:44 UTC
Hi :)
I've found a bug when starts iBrowse 2.4
It crash randomly after few moments before starts.
Can't test with SnoopDos, because it exit from Amiberry.

Regards.

**Comment by FabrizioRadica** [comment] 2020-10-20 07:02
> 
> 
> Hi :)
> I've found a bug when starts iBrowse 2.4
> It crash randomly after few moments before starts.
> Can't test with SnoopDos, because it exit from Amiberry.
> 
> Regards.

same problem with iBrowse 2.5

**Comment by midwan** [comment] 2020-10-28 17:33
I think it's a bug in the filesystem somewhere, because this happens while IBrowse is reading it's cache files.
There's no such problem with other browsers or other network related tools, so I don't think this is network related.

**Comment by amyren1966** [comment] 2020-11-27 19:35
I have not experienced any crashes yet with IBrowse 2.5. I use kick 3.1 (A4000), WB3.9.

**Comment by FabrizioRadica** [comment] 2020-11-27 21:40
> 
> 
> I have not experienced any crashes yet with IBrowse 2.5. I use kick 3.1 (A4000), WB3.9.

from me it freezes once every two times :(
...and i don't know why...

Kickstart 3.1.4 and Amiberry 3.4b on DietPI.

**Comment by Gerbinist** [comment] 2020-12-04 07:32
I had the crashes too with the latest IBrowse. Solution is to enable the FPU (68882 in my case).

**Comment by amyren1966** [comment] 2020-12-06 23:32
I can confirm that it crashes without FPU. My "high-end" Amiga setup use 68030 CPU, 68882 FPU and JIT enabled. I never had IBrowse issues with that setup. Now I tried to disable the FPU, and that caused IBrowse to crash as soon as it started to render a website.

**Comment by midwan** [comment] 2021-01-29 19:55
This seems to be a weird case:
- I cannot get a crash from IBrowse on my 64-bit based, WB 3.9 installation. No matter how many times I (re)start it, it works as expected.
- I can get it to crash under AmiKit however, on the same 64-bit device, under this scenario only: Run it once, close it down, run it again. 
- I cannot get it to crash when using a Debug build - this only happens on Release (optimized) builds.
- When it crashes, it's regardless of the JIT setting.

This specific issue seems to be related to filesystem access, from what I could tell.

**Comment by Koenig70** [comment] 2022-01-24 17:08
I have been suffering this bug for a while. I have solved it changing this in the Ibrowse settings:

-Network--->cache --->disk cache--->SIZE OFF

After this change I can open Ibrowse multiple times without a single crash. Hope this helps if you want to use it with Amyberry.
Cheers.

**Comment by midwan** [comment] 2022-01-24 17:10
Oh, thanks! I had tracked it down to be related to the cache it keeps, but I didn't check the options to see if anything there would help (doh).

**Comment by Koenig70** [comment] 2022-01-24 17:16
Hi Midwan. Great. In fact I read what you already said about reading cache files...so I have been trying different settings and today I came across with this setting. I have been opening Ibrowse more than twenty times (lol) one after another...and no crash on my side. :-)

**Comment by midwan** [comment] 2022-09-24 09:13
This issue has been stale for quite a while now, so I'll close it since we have a workaround.

**Closed by midwan** 2022-09-24 09:13 UTC
Labels: bug
