### ISSUE TITLE
Test Drive 2 - Faulty car selection screen

### ISSUE THREAD

**Issue by Retro1968** [BlitterStudio/amiberry#1000] opened 2022-07-29 09:07 UTC
Raspberry Pi 4, RetroPie 4.8, Amiberry v.5.3 (2022-07-01) running AmigaOS 3.2.1. The WHDLoad games are launched from the workbench.

Hello Dimitris,
I hope you have a nice holiday season. Thanks for your work on amiberry, which allows me to pretend I'm 20 again. ;-)

Since amiberry 5.3, the vehicles in the car selection screen are no longer displayed correctly in Test Drive 2.
Only the statistics for the vehicles are displayed; so the associated image of the vehicle is omitted.
![TD2#1](https://user-images.githubusercontent.com/58906142/181724947-1906c7de-0776-4f36-98da-40b4dc0da920.jpg)

The game itself runs correctly otherwise.
![TD2#2](https://user-images.githubusercontent.com/58906142/181724999-50d73d1d-3490-4259-88d3-6c20a5fd0025.jpg)

Attached are my amiberry.conf and default.uae: 
[configs.zip](https://github.com/BlitterStudio/amiberry/files/9218462/configs.zip)

Cheers
Retro1968

**Comment by nemo93** [comment] 2022-07-30 07:44
Hi @Retro1968 thanks for reporting. There's a case with 5.3 where some settings are not properly applied as they should. Based on config file you've attached I can see the following parameter being turned on: 

```
allow_display_settings_from_xml=yes
```

Meaning games settings should be fetched from an external XML file. This is how it's supposed to work with current Retropie hence all good. However 5.3 seems to apply random settings to some games (need to be refined). If you can't wait for next release feel free to fiddle with the settings straight from the GUI.

I'll test on my end (I don't rely on AmigaOS though) as from top off my head Test Drive 2 doesn't require any specific settings to be set (eg. fast copper or anything blitter related). I'm on 32bit OS also - which is Retropie's default.

**Comment by Retro1968** [comment] 2022-07-30 09:59
Thx for your help. I suggest its a more a problem of the autocrop function of amiberry that i additionally use to get a fullscreen.

**Comment by nemo93** [comment] 2022-08-01 07:59
You may be right as I can't reproduce that issue here on my environment (official Retropie, 32-bit OS, DMX).

**Comment by Retro1968** [comment] 2022-08-15 14:50
I'm surprised you declared the problem resolved. It exists in both the master version and the developer version. In the developer version there is also a guru message when starting testdrive 2

**Comment by midwan** [comment] 2022-08-15 18:07
> I'm surprised you declared the problem resolved. It exists in both the master version and the developer version. In the developer version there is also a guru message when starting testdrive 2

Sorry, closed this by mistake. It looks like an autocrop issue, which is known to be imperfect (which is why it's an option, and can also be triggered manually).

If it works without Autocrop, then the best solution I can think of right now, would be to assign Autocrop to a hotkey (e.g. on the controller), and only trigger it when you want to. Usually that works better, since it forces a re-calculation of the screen when it's triggered.

**Comment by midwan** [comment] 2022-08-15 18:15
Confirmed that this works normally when using the WHDLoad booter (e.g. from RetroPie) and the LHA directly.
Note to @nemo93 - the game doesn't need Horizontal centering, since it uses 720 pixels of width anyway. And the centering messes up the scrolling of sprites, in the car selection screen for example. Disable it, and it's smooth again.

**Comment by midwan** [comment] 2022-08-15 18:19
And also confirmed that this only happens with Autocrop - unfortunately there's no reliable way (that I've found at least) to make it work in all conditions. Cases like this one, will not work properly with auto-crop, so it's best to enable/disable it as needed.

**Closed by midwan** 2022-08-15 18:19 UTC
