### ISSUE TITLE
uae-configuration crashes Amiberry

### ISSUE THREAD

**Issue by MrV2K** [BlitterStudio/amiberry#1110] opened 2023-06-19 16:30 UTC
**Describe the bug**
If you run "uae-configuration cycle_exact true" from the command line Amiberry immediately crashes back to diet-pi

**To Reproduce**
Load workbench. Run `uae-configuration cycle_exact true` from the CLI

**Expected behavior**
The command should set cycle exact 

**Screenshots**
N/A

**Desktop (please complete the following information):**

- OS: Diet-Pi v18.8.2

- Version 5.6

Love Amiberry? Please consider supporting it:
👉  https://ko-fi.com/midwan

**Comment by midwan** [comment] 2023-06-19 17:27
Cycle-Exact is only supported on 68000 configurations. What kind of config are you using when you test this?
Also, there was a bug that could be related in 5.6.0, which got fixed with 5.6.1. It would be worth testing in that latest version to see if the issue is already resolved.

**Comment by MrV2K** [comment] 2023-06-19 18:46
I was using it on an 040 config which explains the problem. I guess that I expected the same behaviour as WinUAE which just ignores it. I can't get 5.6.1 yet as the Dietpi guys haven't added it to the update process.

**Comment by midwan** [comment] 2023-06-19 18:52
@MrV2K I'm sure DietPi will be updated to include it soon, they are usually quite quick.
If it still crashes with 5.6.1, let me know - it certainly shouldn't. :)

**Comment by midwan** [comment] 2023-06-19 18:54
Closing this for now, but feel free to come back to it if the issue persists with 5.6.1

**Closed by midwan** 2023-06-19 18:54 UTC
