### ISSUE TITLE
Cannon Fodder FMV intro - black screen, sound ok

### ISSUE THREAD

**Issue by fuseoppl** [BlitterStudio/amiberry#1226] opened 2024-02-19 09:33 UTC
Black screen while playing the FMV intro in Cannon Fodder. The sound is ok.

- OS: 
Raspbian GNU/Linux 10 (buster)
Linux 5.10.103-v7l+ armv7l
Retropie 4.8

- Hardware:
Raspberry Pi 4 Model B Rev 1.2

- Amiberry version:
5.5.7

- Library:
libmpeg2-4 (0.5.1-8)
mpg123 (1.25.10-2)
libsdl2-2.0-0 (2.0.10+5rpi).

- Config file:
`config_description=
config_hardware=true
config_host=true
config_version=5.6.7
config_hardware_path=
config_host_path=
config_all_path=
vkbd_style=Original
vkbd_language=US
vkbd_transparency=0
vkbd_exit=false
vkbd_hires=false
vkbd_enabled=false
amiberry.rom_path=./
amiberry.floppy_path=./
amiberry.hardfile_path=./
; host-specific
amiberry.middle_mouse=true
amiberry.active_priority=2
amiberry.borderless=true
amiberry.soundcard=0
amiberry.soundcardname=USB Sound Blaster HD, USB Audio
amiberry.gfx_auto_crop=true
amiberry.open_gui=guide
amiberry.quit_amiberry=AudioPlay
amiberry.drawbridge_serial_port=
amiberry.use_retroarch_quit=false
amiberry.use_retroarch_menu=false
amiberry.expansion_gui_page=cd32fmv
amiberry.vkbd_toggle=
; common
use_gui=no
use_debugger=false
kickstart_rom_file=/home/pi/RetroPie/BIOS/amiga/CD32.rom
kickstart_rom_file_id=1E62D4A5,CD32 KS ROM v3.1
kickstart_ext_rom_file=/home/pi/RetroPie/BIOS/amiga/CD32ext.rom
kickstart_ext_rom_file_id=87746BE2,CD32 extended ROM
cd32fmv_rom_file=/home/pi/RetroPie/BIOS/amiga/CD32fmv.rom
cd32fmv_rom_file_id=F11158EB,CD32 Full Motion Video Cartridge ROM
flash_file=/home/pi/RetroPie/roms/amiga/.data/Cannon-Fodder/cd32.nvr
cart_file=/home/pi/RetroPie/BIOS/amiga/CD32fmv.rom
rtc_file=
kickshifter=false
scsidevice_disable=true
floppy_volume=33
floppy0=
floppy0type=-1
floppy1=
floppy1type=-1
floppy2=
floppy3=
cdimage0=/home/pi/RetroPie/roms/amiga/.data/Cannon-Fodder/Cannon Fodder (1993)(Virgin)[!][Amiga-CD32].cue
nr_floppies=0
floppy_speed=100
cd_speed=100
parallel_on_demand=false
serial_on_demand=false
serial_hardware_ctsrts=true
serial_status=true
serial_direct=false
scsi=true
uaeserial=false
sana2=false
sound_output=exact
sound_channels=stereo
sound_stereo_separation=7
sound_stereo_mixing_delay=0
sound_max_buff=8192
sound_frequency=22050
sound_interpol=anti
sound_filter=off
sound_filter_type=enhanced
sound_volume=0
sound_volume_paula=0
sound_volume_cd=0
sound_volume_ahi=0
sound_volume_midi=0
sound_volume_genlock=0
sound_auto=true
sound_stereo_swap_paula=false
sound_stereo_swap_ahi=false
comp_trustbyte=indirect
comp_trustword=indirect
comp_trustlong=indirect
comp_trustnaddr=indirect
comp_nf=true
comp_constjump=true
comp_flushmode=soft
compfpu=false
comp_catchfault=true
cachesize=0
joyport0=mouse
joyport0autofire=none
joyport0mode=mousenowheel
joyportfriendlyname0=System mouse
joyportname0=MOUSE0
joyport1=joy0
joyport1autofire=none
joyport1mode=cd32joy
joyportfriendlyname1=Mad Catz C.T.R.L.R
joyportname1=JOY0
joyport1_amiberry_custom_none_a=Joy2 CD32 Red
joyport1_amiberry_custom_none_b=Joy2 CD32 Blue
joyport1_amiberry_custom_none_x=Joy2 CD32 Green
joyport1_amiberry_custom_none_y=Joy2 CD32 Yellow
joyport1_amiberry_custom_none_start=Joy2 CD32 Play
joyport1_amiberry_custom_none_leftshoulder=Joy2 CD32 RWD
joyport1_amiberry_custom_none_rightshoulder=Joy2 CD32 FFW
bsdsocket_emu=false
synchronize_clock=false
maprom=0x0
boot_rom_uae=disabled
parallel_postscript_emulation=false
parallel_postscript_detection=false
ghostscript_parameters=
parallel_autoflush=5
uae_hide_autoconfig=true
gfx_display=0
gfx_display_rtg=0
gfx_framerate=1
gfx_width=720
gfx_height=568
gfx_x_windowed=0
gfx_y_windowed=0
gfx_width_windowed=720
gfx_height_windowed=568
gfx_width_fullscreen=800
gfx_height_fullscreen=600
gfx_refreshrate=0
gfx_autoresolution=0
gfx_autoresolution_vga=true
gfx_backbuffers=2
gfx_backbuffers_rtg=1
gfx_vsync=false
gfx_vsyncmode=normal
gfx_vsync_picasso=false
gfx_vsyncmode_picasso=normal
gfx_lores=false
gfx_resolution=hires
gfx_lores_mode=normal
gfx_flickerfixer=false
gfx_linemode=none
gfx_fullscreen_amiga=false
gfx_fullscreen_picasso=false
gfx_center_horizontal=none
gfx_center_vertical=none
gfx_colour_mode=32bit
gfx_blacker_than_black=false
gfx_api=direct3d11
gfx_api_options=hardware
immediate_blits=false
waiting_blits=automatic
fast_copper=false
multithreaded_drawing=true
ntsc=false
genlock=false
chipset=aga
chipset_refreshrate=49.920410
collision_level=playfields
chipset_compatible=CD32
rtc=none
cia_overlay=false
ksmirror_e0=false
ksmirror_a8=true
cd32cd=true
cd32c2p=true
cd32nvram=true
resetwarning=false
unmapped_address_space=zero
eclocksync=Gayle
cd32fmv=true
z3mapping=real
fastmem_size=0
mem25bit_size=0
a3000mem_size=0
mbresmem_size=0
z3mem_size=0
z3mem_start=0x0
bogomem_size=0
gfxcard_hardware_vblank=false
gfxcard_hardware_sprite=false
gfxcard_multithread=false
chipmem_size=4
cpu_speed=max
cpu_throttle=0.0
cpu_type=68020
cpu_model=68020
cpu_compatible=true
cpu_24bit_addressing=false
cpu_data_cache=false
cpu_cycle_exact=false
cpu_memory_cycle_exact=false
blitter_cycle_exact=false
cycle_exact=false
fpu_strict=false
rtg_nocustom=true
rtg_modes=0x112
debug_mem=false
log_illegal_mem=false
kbd_lang=us
input.config=0
input.joymouse_speed_analog=100
input.joymouse_speed_digital=10
input.joymouse_deadzone=33
input.joystick_deadzone=33
input.analog_joystick_multiplier=18
input.analog_joystick_offset=-5
input.mouse_speed=100
input.autofire_speed=0
input.autoswitch=false
; *** WHDLoad Booter. Options
whdload_slave=
whdload_showsplash=true
whdload_buttonwait=false
whdload_custom1=0
whdload_custom2=0
whdload_custom3=0
whdload_custom4=0
whdload_custom5=0
whdload_custom=
whdload_writecache=false
whdload_quit_on_exit=false
`

**Comment by solskogen** [comment] 2024-02-19 09:41
Does it happen on newer than buster?

**Comment by fuseoppl** [comment] 2024-02-19 09:46
> Does it happen on newer than buster?

I have to buy a memory card and install the latest system, but I remember that on an older system and of course an older Amiberry I managed to run this intro correctly, but it was a few years ago and I don't know if I'm doing something wrong now or if there is actually a problem . I will check it on a newer system within 2-3 days.

**Comment by midwan** [comment] 2024-02-19 14:08
I can recreate this, if the FMV rom is enabled.
However, the same thing seems to happen in the latest WinUAE also, so perhaps it's an upstream bug that was introduced there, and got merged into Amiberry with the updates.

**Comment by midwan** [comment] 2024-02-19 15:21
Actually, I'm not sure this _ever_ worked properly.
I tested up to v3.3 on the RPI5 here, and all versions have the same behavior (black screen when the video is playing). Only the WIP `gfx-rewrite` branch shows something, and even there it's incorrect (wrong colors and the frames are not updated until you manually trigger a refresh).

I'm flagging this as a bug to look into.

**Comment by midwan** [comment] 2024-02-19 20:07
If found out a bit more information.
It seems the issue is _only_ with FMV that uses the CD32 FMV module, like the Cannon Fodder sequence.
There are other CD32 titles that use "FMV", but they are just animations stored in the CD, and play back using the Amiga chipset - those still work. It's only the MPEG-2 encoded sequences that will _only_ play if you add the FMV module to the CD32 config, that are affected.

So far, I've only seen Cannon Fodder doing that. I'll test some more CD32 titles (found a list here: https://en.wikipedia.org/wiki/List_of_Amiga_CD32_games) that have FMV sequences to see if I can find more, but this would explain why it has gone undetected for so long.

**Comment by midwan** [comment] 2024-02-19 21:35
After searching some more, it seems that there isn't really anything else out there using the FMV module in games. The only other usage is VideoCD playback, which for the scope of this emulator, seems a little redundant. 

Furthermore, the code that Toni used for decoding the MPEG-2 video stream is based on a custom `libmpeg` version from `ffmpeg` (https://github.com/tonioni/WinUAE/pull/17#issuecomment-50335355), which has since been deprecated and removed from `ffmpeg` itself.

All in all, it seems this feature is not very useful in real life.

**Comment by fuseoppl** [comment] 2024-02-20 13:44
> All in all, it seems this feature is not very useful in real life.

I also tried to watch the image of the Final Mission movie, there is no image either. It's true that it is of very little use, although I was hoping that it would be something simple to fix and would work, but there are certainly many other more important problems to solve. Regards

**Comment by midwan** [comment] 2024-02-20 21:52
For what it's worth, it's somewhat working in the `preview` branch now, after the latest changes.
But the colors are incorrect, and I couldn't find a way to fix them. It looks like a BGR vs RGB problem, where the Red and Blue are swapped.

I could play back a sample VideoCD normally, though the FMV intro of Cannon Fodder is still buggy.

**Closed** 2024-02-20 22:00 UTC
Labels: bug, fixed in preview

**Comment by fuseoppl** [comment] 2024-02-21 12:08
maybe someday, when there will be time, it will be possible to fix it, although in fact it is the least needed function :)
